version: "3"

networks:
  backend:

services:
  db:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend

  backend-directus:
    image: directus/next:v9.0.0-rc.5
    env_file: .env
    ports:
      - "8055:8055"
    networks:
      - backend
