FROM directus/next:v9.0.0-rc.3

ENV PORT=80
ENV PUBLIC_URL="/"

ENV RATE_LIMITER_ENABLED=false
ENV RATE_LIMITER_STORE=memory
ENV RATE_LIMITER_POINTS=25
ENV RATE_LIMITER_DURATION=1

ENV CACHE_ENABLED=false

ENV ACCESS_TOKEN_TTL="15m"
ENV REFRESH_TOKEN_TTL="7d"
ENV REFRESH_TOKEN_COOKIE_SECURE=false
ENV REFRESH_TOKEN_COOKIE_SAME_SITE="lax"

ENV OAUTH_PROVIDERS=""

ENV KEY="5957be82-8c7d-45c0-9251-a23879224067"
ENV SECRET="lQtLbrovvvCpsx_ADh0qInKYxPUOW93z"

EXPOSE 80
